 - name: Install postgresql
   apt: name=postgresql state=present
   register: postgresql
 
 - name: Create openerp user
   postgresql_user: name={{ odoo_user }} role_attr_flags=SUPERUSER state=present
   sudo: yes
   sudo_user: postgres
