 - name: Crear directorio ssh
   file: state=directory mode=0700 dest=/root/.ssh/
   
 - name: Agregar la llave publica del hub
   copy: src=~/.ssh/id_rsa.pub dest=/root/.ssh/authorized_keys owner=root mode=0600
   register: rsa
   ignore_errors: yes 
   
 - name: base debian packages
   apt: name={{ item }} state=present
   with_items:
     - sudo
     - git
     - screen
     - less
     - lsof
     - python-setuptools
     - python-psycopg2
